# Generated by Django 5.1.7 on 2025-04-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceopportunity',
            name='category',
            field=models.CharField(choices=[('scholarships', 'Scholarships'), ('internships', 'Internships'), ('jobs', 'Jobs'), ('courses', 'Courses'), ('events', 'Events')], max_length=50),
        ),
    ]
