# Generated by Django 5.1.6 on 2025-04-25 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alumni_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
