# Generated by Django 5.1.7 on 2025-04-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_resourceopportunity_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
                ('next_role', models.CharField(max_length=100)),
                ('avg_years', models.IntegerField()),
                ('salary_range', models.CharField(max_length=100)),
                ('skills_required', models.TextField()),
            ],
        ),
    ]
